using System;
using System.Collections.Generic;
using CerberusWareV3.Configuration;
using CerberusWareV3.Localization;
public static class LocalizationManager
{
	private static string GetRawString(string key)
	{
		Language currentLanguage = CerberusConfig.Settings.CurrentLanguage;
		string text;
		if (currentLanguage == Language.En && new Dictionary<string, string>
		{
			{ "AimBot_Gun_AutoBolt", "Auto Bolt" },
			{ "AimBot_Gun_AutoPredict", "Auto Predict" },
			{ "AimBot_Gun_AutoReload", "Auto Reload" },
			{ "AimBot_Gun_AutoReloadDelay", "Auto Reload Delay" },
			{ "AimBot_Gun_Circle", "Circle" },
			{ "AimBot_Gun_Color", "Color" },
			{ "AimBot_Gun_Critical", "Critical" },
			{ "AimBot_Gun_Enabled", "Enabled" },
			{ "AimBot_Gun_EnabledHelper", "Enabled Helper" },
			{ "AimBot_Gun_General", "General" },
			{ "AimBot_Gun_Helpers", "Helpers" },
			{ "AimBot_Gun_HitScan", "Hit Scan" },
			{ "AimBot_Gun_Line", "Line" },
			{ "AimBot_Gun_MinimalSpread", "Minimal Spread" },
			{ "AimBot_Gun_Predict", "Predict" },
			{ "AimBot_Gun_PredictCorrection", "Predict Correction" },
			{ "AimBot_Gun_Priority", "Priority" },
			{ "AimBot_Gun_Radius", "Radius" },
			{ "AimBot_Gun_ShowAmmo", "Show Ammo" },
			{ "AimBot_Gun_Visual", "Visual" },
			{ "AimBot_Melee_Attack360", "Attack 360" },
			{ "AimBot_Melee_AutoAttack", "Auto Attack" },
			{ "AimBot_Melee_Circle", "Circle" },
			{ "AimBot_Melee_Color", "Color" },
			{ "AimBot_Melee_Critical", "Critical" },
			{ "AimBot_Melee_Enabled", "Enabled" },
			{ "AimBot_Melee_EnabledHelper", "Enabled Helper" },
			{ "AimBot_Melee_FixDelay", "Fix Delay" },
			{ "AimBot_Melee_FixNetworkDelay", "Fix Network Delay" },
			{ "AimBot_Melee_General", "General" },
			{ "AimBot_Melee_Helpers", "Helpers" },
			{ "AimBot_Melee_Line", "Line" },
			{ "AimBot_Melee_Priority", "Priority" },
			{ "AimBot_Melee_Radius", "Radius" },
			{ "AimBot_Melee_RotateToTarget", "Rotate To Target" },
			{ "AimBot_Melee_Visual", "Visual" },
			{ "AimBot_OnlyPriority", "Only Priority" },
			{ "AimBot_TargetPriority_DistanceToMouse", "Distance To Mouse" },
			{ "AimBot_TargetPriority_DistanceToPlayer", "Distance To Player" },
			{ "AimBot_TargetPriority_LowestHealth", "Lowest Health" },
			{ "ESP_NoSlip", "No Slip" },
			{ "ESP_Weapon", "Weapon" },
			{ "Keybind_FOV", "FOV" },
			{ "Keybind_Fire", "Fire" },
			{ "Keybind_FullBright", "FullBright" },
			{ "Keybind_HeavyAttack", "Heavy Attack" },
			{ "Keybind_LightAttack", "Light Attack" },
			{ "Keybind_OpenSettings", "Open Settings" },
			{ "Keybind_StorageViewer", "Storage Viewer" },
			{ "Keybind_Zoom_Down", "Down" },
			{ "Keybind_Zoom_Up", "Up" },
			{ "Misc_General_AntiAFK", "Anti AFK" },
			{ "Misc_General_AntiAim", "Anti Aim" },
			{ "Misc_General_AntiSoap", "Anti Soap" },
			{ "Misc_General_DamageOverlay", "Damage Overlay" },
			{ "Misc_General_OpenFolder", "Open Folder" },
			{ "Misc_General_SearchingItems", "Searching Items" },
			{ "Misc_General_SearchingItems_Add", "Add" },
			{ "Misc_General_SearchingItems_Enabled", "Enabled" },
			{ "Misc_General_SearchingItems_ShowName", "Show Name" },
			{ "Misc_General_ShowExplosions", "Show Explosions" },
			{ "Misc_General_ShowTrajectory", "Show Trajectory" },
			{ "Misc_General_Speed", "Speed" },
			{ "Misc_General_Translator", "Translator" },
			{ "Misc_General_Translator_LanguageChat", "Language Chat" },
			{ "Misc_General_Translator_TranslateChat", "Translate Chat" },
			{ "Misc_General_TrashTalk", "Trash Talk" },
			{ "Misc_Spammer_AHelp", "AHelp" },
			{ "Misc_Spammer_AHelp_Delay", "Delay" },
			{ "Misc_Spammer_AHelp_Enabled", "Enabled" },
			{ "Misc_Spammer_AHelp_Text", "Text" },
			{ "Misc_Spammer_Chat", "Chat" },
			{ "Misc_Spammer_Chat_Delay", "Delay" },
			{ "Misc_Spammer_Chat_Enabled", "Enabled" },
			{ "Misc_Spammer_Chat_Text", "Text" },
			{ "Misc_Spammer_Settings", "Settings" },
			{ "Misc_Spammer_Settings_Length", "Length" },
			{ "Misc_Spammer_Settings_ProtectWord", "Protect Word" },
			{ "Misc_Spammer_Settings_RandomLength", "Random Length" },
			{ "Players_General_Character", "Character" },
			{ "Players_General_Entity", "Entity" },
			{ "Players_General_Name", "Name" },
			{ "Players_General_SearchHint", "Search Hint" },
			{ "Players_General_SortBy", "Sort By" },
			{ "Players_General_Status", "Status" },
			{ "Players_Logs_Title", "Title" },
			{ "Players_WindowTitle", "Window Title" },
			{ "Players_Window_Job", "Job" },
			{ "Players_Window_LastPosition", "Last Position" },
			{ "Players_Window_Name", "Name" },
			{ "Players_Window_NoPreview", "No Preview" },
			{ "Settings_General", "General" },
			{ "Settings_General_SwitchToEnglish", "Switch To English" },
			{ "Settings_General_SwitchToRussian", "Switch To Russian" },
			{ "Settings_General_Unload", "Unload" },
			{ "Settings_Patches", "Patches" },
			{ "Settings_Patches_AdminPrivilege", "Admin Privilege" },
			{ "Settings_Patches_AntiScreenGrub", "Anti Screen Grab" },
			{ "Settings_Patches_NoDamageForceSay", "No Damage ForceSay" },
			{ "Settings_Patches_NoDamageFriend", "No Damage Friend" },
			{ "Settings_ShowMenu", "Show Menu" },
			{ "Settings_UICustomizable", "Notification Customizable" },
			{ "Visuals_ESP_Antag", "Antag" },
			{ "Visuals_ESP_CKey", "CKey" },
			{ "Visuals_ESP_Color_Antag", "Antag" },
			{ "Visuals_ESP_Color_CKey", "CKey" },
			{ "Visuals_ESP_Color_CombatMode", "Combat Mode" },
			{ "Visuals_ESP_Color_Contraband", "Contraband" },
			{ "Visuals_ESP_Color_Friend", "Friend" },
			{ "Visuals_ESP_Color_Implants", "Implants" },
			{ "Visuals_ESP_Color_Name", "Name" },
			{ "Visuals_ESP_Color_Priority", "Priority" },
			{ "Visuals_ESP_Colors", "Colors" },
			{ "Visuals_ESP_CombatMode", "Combat Mode" },
			{ "Visuals_ESP_Contraband", "Contraband" },
			{ "Visuals_ESP_Enabled", "Enabled" },
			{ "Visuals_ESP_Font", "Font" },
			{ "Visuals_ESP_Font_Interval", "Interval" },
			{ "Visuals_ESP_Font_MainFont", "Main Font" },
			{ "Visuals_ESP_Font_OtherFont", "Other Font" },
			{ "Visuals_ESP_Font_Size", "Size" },
			{ "Visuals_ESP_Font_Size_Other", "Other" },
			{ "Visuals_ESP_Friend", "Friend" },
			{ "Visuals_ESP_General", "General" },
			{ "Visuals_ESP_Implants", "Implants" },
			{ "Visuals_ESP_Name", "Name" },
			{ "Visuals_ESP_Priority", "Priority" },
			{ "Visuals_Eye_FOV", "FOV" },
			{ "Visuals_Eye_FullBright", "FullBright" },
			{ "Visuals_Eye_General", "General" },
			{ "Visuals_Eye_HUD", "HUD" },
			{ "Visuals_Eye_HUD_AntagIcons", "Antag Icons" },
			{ "Visuals_Eye_HUD_ChemicalAnalysis", "Chemical Analysis" },
			{ "Visuals_Eye_HUD_Color", "Color" },
			{ "Visuals_Eye_HUD_CriminalRecordIcons", "Criminal Record Icons" },
			{ "Visuals_Eye_HUD_Health", "Health" },
			{ "Visuals_Eye_HUD_JobIcons", "Job Icons" },
			{ "Visuals_Eye_HUD_MindShieldIcons", "Mind Shield Icons" },
			{ "Visuals_Eye_HUD_ShowElectrocution", "Show Electrocution" },
			{ "Visuals_Eye_HUD_Stamina", "Stamina" },
			{ "Visuals_Eye_HUD_SyndicateIcons", "Syndicate Icons" },
			{ "Visuals_Eye_Patches", "Patches" },
			{ "Visuals_Eye_Patches_NoBadOverlays", "No Bad Overlays" },
			{ "Visuals_Eye_Patches_NoCameraRecoil", "No Camera Recoil" },
			{ "Visuals_Eye_Patches_NoClyde", "No Clyde" },
			{ "Visuals_Eye_Patches_NoSmoke", "No Smoke" },
			{ "Visuals_Eye_Reset", "Reset" },
			{ "Visuals_Eye_StorageViewer", "Storage Viewer" },
			{ "Visuals_Eye_StorageViewer_Color", "Color" },
			{ "Visuals_Eye_StorageViewer_Enabled", "Enabled" },
			{ "Visuals_Eye_Zoom", "Zoom" },
			{ "Visuals_Fun_Color", "Color" },
			{ "Visuals_Fun_Enabled", "Enabled" },
			{ "Visuals_Fun_Filters", "Filters" },
			{ "Visuals_Fun_Filters_Mobs", "Mobs" },
			{ "Visuals_Fun_Filters_Others", "Others" },
			{ "Visuals_Fun_Filters_Player", "Player" },
			{ "Visuals_Fun_General", "General" },
			{ "Visuals_Fun_Jump", "Jump" },
			{ "Visuals_Fun_Rainbow", "Rainbow" },
			{ "Visuals_Fun_Rotation", "Rotation" },
			{ "Visuals_Fun_Snake", "Snake" },
			{ "Visuals_Fun_Speed", "Speed" },
			{ "Visuals_Fun_TextureOverlay", "Texture Overlay" },
			{ "Visuals_Fun_TextureOverlay_Enabled", "Enabled" },
			{ "Visuals_Fun_TextureOverlay_Invisible", "Invisible" },
			{ "Visuals_Fun_TextureOverlay_OpenFolder", "Open Folder" },
			{ "Visuals_Fun_TextureOverlay_Size", "Size" },
			{ "UiSettings_Title", "Notifications Settings" },
			{ "UiSettings_EnableNotifications", "Enable Notifications" },
			{ "UiSettings_MaxNotifications", "Max Notifications" },
			{ "UiSettings_NotificationSize", "Notification Size" },
			{ "UiSettings_NotificationSize_Small", "Small" },
			{ "UiSettings_NotificationSize_Medium", "Medium" },
			{ "UiSettings_NotificationSize_Large", "Large" },
			{ "UiSettings_IgnoreSizeCheck", "Ignore Size Check" },
			{ "Notification_TestMessage", "This is a test notification." },
			{ "Configs_Title", "" },
			{ "Configs_Name", "Config Name" },
			{ "Configs_Save", "Save to Folder" },
			{ "Configs_Load", "Load from Folder" },
			{ "Configs_Delete", "Delete from Folder" },
			{ "Configs_OpenFolder", "Open folder" },
			{ "Main_Gun", "Gun" },
			{ "Main_Melee", "Melee" },
			{ "Main_Esp", "ESP" },
			{ "Main_Eye", "Eye" },
			{ "Main_Fun", "Fun" },
			{ "Main_Players", "Players" },
			{ "Main_Logs", "Logs" },
			{ "Main_Misc", "Misc" },
			{ "Main_Spammer", "Spammer" },
			{ "Main_Settings", "Settings" },
			{ "Main_Configs", "Configs" }
		}.TryGetValue(key, out text))
		{
			return text;
		}
		if (currentLanguage == Language.Ru && new Dictionary<string, string>
		{
			{ "AimBot_Gun_AutoBolt", "Авто Затвор" },
			{ "AimBot_Gun_AutoPredict", "Авто Предикт" },
			{ "AimBot_Gun_AutoReload", "Авто Перезарядка" },
			{ "AimBot_Gun_AutoReloadDelay", "Задержка Авто Перезарядки" },
			{ "AimBot_Gun_Circle", "Круг" },
			{ "AimBot_Gun_Color", "Цвет" },
			{ "AimBot_Gun_Critical", "Крит" },
			{ "AimBot_Gun_Enabled", "Включено" },
			{ "AimBot_Gun_EnabledHelper", "Помощь" },
			{ "AimBot_Gun_General", "Общее" },
			{ "AimBot_Gun_Helpers", "" },
			{ "AimBot_Gun_HitScan", "Хитскан" },
			{ "AimBot_Gun_Line", "Линия" },
			{ "AimBot_Gun_MinimalSpread", "Минимальный Разброс" },
			{ "AimBot_Gun_Predict", "Предикт" },
			{ "AimBot_Gun_PredictCorrection", "Коррекция Предикта" },
			{ "AimBot_Gun_Priority", "Приоритет" },
			{ "AimBot_Gun_Radius", "Радиус" },
			{ "AimBot_Gun_ShowAmmo", "Показывать Патроны" },
			{ "AimBot_Gun_Visual", "Визуал" },
			{ "AimBot_Melee_Attack360", "Атака 360 Градусов" },
			{ "AimBot_Melee_AutoAttack", "Авто Атака" },
			{ "AimBot_Melee_Circle", "Круг" },
			{ "AimBot_Melee_Color", "Цвет" },
			{ "AimBot_Melee_Critical", "Крит" },
			{ "AimBot_Melee_Enabled", "Включено" },
			{ "AimBot_Melee_EnabledHelper", "Помощь" },
			{ "AimBot_Melee_FixDelay", "Фикс Задержки" },
			{ "AimBot_Melee_FixNetworkDelay", "Фикс Сетевой Задержки" },
			{ "AimBot_Melee_General", "Общие" },
			{ "AimBot_Melee_Helpers", "" },
			{ "AimBot_Melee_Line", "Линия" },
			{ "AimBot_Melee_Priority", "Приоритет" },
			{ "AimBot_Melee_Radius", "Радиус" },
			{ "AimBot_Melee_RotateToTarget", "Поворот к Цели" },
			{ "AimBot_Melee_Visual", "Визуал" },
			{ "AimBot_OnlyPriority", "Только Приоритет" },
			{ "AimBot_TargetPriority_DistanceToMouse", "Расстояние до Курсора" },
			{ "AimBot_TargetPriority_DistanceToPlayer", "Расстояние до Игрока" },
			{ "AimBot_TargetPriority_LowestHealth", "Минимальное здоровье" },
			{ "ESP_NoSlip", "Ноуслип" },
			{ "ESP_Weapon", "Оружие" },
			{ "Keybind_FOV", "Поле зрения" },
			{ "Keybind_Fire", "Огонь" },
			{ "Keybind_FullBright", "Фуллбрайт" },
			{ "Keybind_HeavyAttack", "Тяжелая Атака" },
			{ "Keybind_LightAttack", "Легкая Атака" },
			{ "Keybind_OpenSettings", "Открыть Настройки" },
			{ "Keybind_StorageViewer", "Отрисовка Хранилища" },
			{ "Keybind_Zoom_Down", "Уменьшить" },
			{ "Keybind_Zoom_Up", "Увеличить" },
			{ "Misc_General_AntiAFK", "Анти Афк" },
			{ "Misc_General_AntiAim", "Анти Аим" },
			{ "Misc_General_AntiSoap", "Анти Мыло" },
			{ "Misc_General_DamageOverlay", "Индикатор урона" },
			{ "Misc_General_OpenFolder", "Открыть Папку" },
			{ "Misc_General_SearchingItems", "Поиск предметов" },
			{ "Misc_General_SearchingItems_Add", "Добавить" },
			{ "Misc_General_SearchingItems_Enabled", "Включено" },
			{ "Misc_General_SearchingItems_ShowName", "Показать Название" },
			{ "Misc_General_ShowExplosions", "Показывать Взрывы" },
			{ "Misc_General_ShowTrajectory", "Показать Траекторию" },
			{ "Misc_General_Speed", "Скорость" },
			{ "Misc_General_Translator", "Переводчик" },
			{ "Misc_General_Translator_LanguageChat", "Язык чата" },
			{ "Misc_General_Translator_TranslateChat", "Перевод чата" },
			{ "Misc_General_TrashTalk", "Треш Толк" },
			{ "Misc_Spammer_AHelp", "Ахелп" },
			{ "Misc_Spammer_AHelp_Delay", "Задержка" },
			{ "Misc_Spammer_AHelp_Enabled", "Включено" },
			{ "Misc_Spammer_AHelp_Text", "Текст" },
			{ "Misc_Spammer_Chat", "Чат" },
			{ "Misc_Spammer_Chat_Delay", "Задержка" },
			{ "Misc_Spammer_Chat_Enabled", "Включено" },
			{ "Misc_Spammer_Chat_Text", "Текст" },
			{ "Misc_Spammer_Settings", "Настройки" },
			{ "Misc_Spammer_Settings_Length", "Длина" },
			{ "Misc_Spammer_Settings_ProtectWord", "Защитное Слово" },
			{ "Misc_Spammer_Settings_RandomLength", "Рандомная Длина" },
			{ "Players_General_Character", "Персонаж" },
			{ "Players_General_Entity", "Сущность" },
			{ "Players_General_Name", "Имя" },
			{ "Players_General_SearchHint", "Поиск по" },
			{ "Players_General_SortBy", "Сортировка по" },
			{ "Players_General_Status", "Статус" },
			{ "Players_Logs_Title", "" },
			{ "Players_WindowTitle", "" },
			{ "Players_Window_Job", "Профессия" },
			{ "Players_Window_LastPosition", "Последняя Позиция" },
			{ "Players_Window_Name", "Имя" },
			{ "Players_Window_NoPreview", "Без Превью" },
			{ "Settings_General", "Общие" },
			{ "Settings_General_SwitchToEnglish", "Переключить на Английский" },
			{ "Settings_General_Unload", "Выгрузить" },
			{ "Settings_Patches", "Патчи" },
			{ "Settings_Patches_AdminPrivilege", "Привилегии администратора" },
			{ "Settings_Patches_AntiScreenGrub", "Анти Скрин Граб" },
			{ "Settings_Patches_NoDamageForceSay", "Без Крика при ForceSay" },
			{ "Settings_Patches_NoDamageFriend", "Анти Френдли Фаер" },
			{ "Settings_ShowMenu", "Показать меню" },
			{ "Settings_UICustomizable", "Настройка Уведомлений" },
			{ "Visuals_ESP_Antag", "Антаг" },
			{ "Visuals_ESP_CKey", "Сикей" },
			{ "Visuals_ESP_Color_Antag", "Антаг" },
			{ "Visuals_ESP_Color_CKey", "Сикей" },
			{ "Visuals_ESP_Color_CombatMode", "Боевой Режим" },
			{ "Visuals_ESP_Color_Contraband", "Контрабанда" },
			{ "Visuals_ESP_Color_Friend", "Союзник" },
			{ "Visuals_ESP_Color_Implants", "Импланты" },
			{ "Visuals_ESP_Color_Name", "Имя" },
			{ "Visuals_ESP_Color_Priority", "Приоритет" },
			{ "Visuals_ESP_Colors", "Colors" },
			{ "Visuals_ESP_CombatMode", "Боевой Режим" },
			{ "Visuals_ESP_Contraband", "Контрабанда" },
			{ "Visuals_ESP_Enabled", "Включено" },
			{ "Visuals_ESP_Font", "Шрифт" },
			{ "Visuals_ESP_Font_Interval", "Интервал" },
			{ "Visuals_ESP_Font_MainFont", "Основной шрифт" },
			{ "Visuals_ESP_Font_OtherFont", "Дополнительный шрифт" },
			{ "Visuals_ESP_Font_Size", "Размер" },
			{ "Visuals_ESP_Font_Size_Other", "Доп. размер" },
			{ "Visuals_ESP_Friend", "Союзник" },
			{ "Visuals_ESP_General", "Общие" },
			{ "Visuals_ESP_Implants", "Импланты" },
			{ "Visuals_ESP_Name", "Имя" },
			{ "Visuals_ESP_Priority", "Приоритет" },
			{ "Visuals_Eye_FOV", "Поле зрения" },
			{ "Visuals_Eye_FullBright", "Фуллбрайт" },
			{ "Visuals_Eye_General", "Общие" },
			{ "Visuals_Eye_HUD", "Худ" },
			{ "Visuals_Eye_HUD_AntagIcons", "Иконки Антагонистов" },
			{ "Visuals_Eye_HUD_ChemicalAnalysis", "Химический анализ" },
			{ "Visuals_Eye_HUD_Color", "Цвет" },
			{ "Visuals_Eye_HUD_CriminalRecordIcons", "Криминальные записи" },
			{ "Visuals_Eye_HUD_Health", "Здоровье" },
			{ "Visuals_Eye_HUD_JobIcons", "Иконки Профессий" },
			{ "Visuals_Eye_HUD_MindShieldIcons", "Иконки защиты разума" },
			{ "Visuals_Eye_HUD_ShowElectrocution", "Показывать Элек..что блять?" },
			{ "Visuals_Eye_HUD_Stamina", "Стамина" },
			{ "Visuals_Eye_HUD_SyndicateIcons", "Иконки Синдиката" },
			{ "Visuals_Eye_Patches", "Исправления" },
			{ "Visuals_Eye_Patches_NoBadOverlays", "Убрать Эффекты" },
			{ "Visuals_Eye_Patches_NoCameraRecoil", "Камера Без Отдачи" },
			{ "Visuals_Eye_Patches_NoClyde", "Без Клайда" },
			{ "Visuals_Eye_Patches_NoSmoke", "Без Дыма" },
			{ "Visuals_Eye_Reset", "Сброс" },
			{ "Visuals_Eye_StorageViewer", "Обзор хранилища" },
			{ "Visuals_Eye_StorageViewer_Color", "Цвет" },
			{ "Visuals_Eye_StorageViewer_Enabled", "Включено" },
			{ "Visuals_Eye_Zoom", "Увеличение" },
			{ "Visuals_Fun_Color", "Цвет" },
			{ "Visuals_Fun_Enabled", "Включено" },
			{ "Visuals_Fun_Filters", "Фильтры" },
			{ "Visuals_Fun_Filters_Mobs", "Мобы" },
			{ "Visuals_Fun_Filters_Others", "Другие" },
			{ "Visuals_Fun_Filters_Player", "Игроки" },
			{ "Visuals_Fun_General", "Общие" },
			{ "Visuals_Fun_Jump", "Прыжок" },
			{ "Visuals_Fun_Rainbow", "Радуга" },
			{ "Visuals_Fun_Rotation", "Вращение" },
			{ "Visuals_Fun_Snake", "Змейка" },
			{ "Visuals_Fun_Speed", "Скорость" },
			{ "Visuals_Fun_TextureOverlay", "Наложение текстуры" },
			{ "Visuals_Fun_TextureOverlay_Enabled", "Включено" },
			{ "Visuals_Fun_TextureOverlay_Invisible", "Невидимо" },
			{ "Visuals_Fun_TextureOverlay_OpenFolder", "Открыть Папку" },
			{ "Visuals_Fun_TextureOverlay_Size", "Размер" },
			{ "UiSettings_Title", "Настройки уведомлений" },
			{ "UiSettings_EnableNotifications", "Включить уведомления" },
			{ "UiSettings_MaxNotifications", "Максимальное Кол-во Уведомлений" },
			{ "UiSettings_NotificationSize", "Размер уведомлений" },
			{ "UiSettings_NotificationSize_Small", "Маленький" },
			{ "UiSettings_NotificationSize_Medium", "Средний" },
			{ "UiSettings_NotificationSize_Large", "Большой" },
			{ "UiSettings_IgnoreSizeCheck", "Игнорировать размер" },
			{ "Notification_TestMessage", "Это тестовое уведомление" },
			{ "Configs_Title", "" },
			{ "Configs_Name", "Имя Конфига" },
			{ "Configs_Save", "Сохранить" },
			{ "Configs_Load", "Загрузить" },
			{ "Configs_Delete", "Удалить" },
			{ "Configs_OpenFolder", "Открыть Папку" },
			{ "Main_Gun", "Оружие" },
			{ "Main_Melee", "Ближний" },
			{ "Main_Esp", "Обзор" },
			{ "Main_Eye", "Глаза" },
			{ "Main_Fun", "Веселое" },
			{ "Main_Players", "Игроки" },
			{ "Main_Logs", "Логи" },
			{ "Main_Misc", "Остальное" },
			{ "Main_Spammer", "Спам" },
			{ "Main_Settings", "Настройки" },
			{ "Main_Configs", "Конфиги" }
		}.TryGetValue(key, out text))
		{
			return text;
		}
		return key;
	}
	public static string GetString(string key)
	{
		return LocalizationManager.GetRawString(key);
	}
	public static string GetString(string key, params object[] args)
	{
		string rawString = LocalizationManager.GetRawString(key);
		string text;
		if (args.Length == 0 || rawString == key)
		{
			text = rawString;
		}
		else
		{
			text = string.Format(rawString, args);
		}
		return text;
	}
	public static void Switch()
	{
		CerberusConfig.Settings.CurrentLanguage = ((CerberusConfig.Settings.CurrentLanguage == Language.Ru) ? Language.En : Language.Ru);
	}
}
